INSERT INTO stylish.products (id, category, title, description, price, texture, wash, place, note, story, main_image) VALUES (1, 'men', '厚實毛呢格子外套', '高抗寒素材選用，保暖也時尚有型', 2200.00, '棉、聚脂纖維', '手洗（水溫40度', '韓國', '實品顏色以單品照為主', '你絕對不能錯過的超值商品', 'uploads\\\\man1.jpg');
INSERT INTO stylish.products (id, category, title, description, price, texture, wash, place, note, story, main_image) VALUES (2, 'women', '前開衩扭結洋裝', '厚薄：薄\\r\\n彈性：無', 799.00, '棉 100%', '手洗，溫水', '中國', '實品顏色依單品照為主', 'O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.', 'uploads\\\\woman1.jpg');
INSERT INTO stylish.products (id, category, title, description, price, texture, wash, place, note, story, main_image) VALUES (3, 'women', '精緻扭結洋裝', '厚薄：薄\\r\\n彈性：無', 999.00, '棉 100%', '手洗', '越南', '實品顏色依單品照為主', 'O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.', 'uploads\\\\woman2.jpg');
INSERT INTO stylish.products (id, category, title, description, price, texture, wash, place, note, story, main_image) VALUES (4, 'women', '木耳邊造型滿版緹花設計上衣', '厚薄：薄\\r\\n彈性：無', 255.00, '棉 100%', '手洗', '越南', '實品顏色依單品照為主', 'O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.', 'uploads\\\\woman3.jpg');
INSERT INTO stylish.products (id, category, title, description, price, texture, wash, place, note, story, main_image) VALUES (5, 'women', '質感立體壓紋設計傘擺背心', '厚薄：薄\\r\\n彈性：無', 400.00, '棉 100%', '手洗', '越南', '實品顏色依單品照為主', 'O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.', 'uploads\\\\woman4.jpg');
INSERT INTO stylish.products (id, category, title, description, price, texture, wash, place, note, story, main_image) VALUES (6, 'women', '鏤空格紋設計微透膚襯衫 ', '厚薄：薄\\r\\n彈性：無', 700.00, '棉 100%', '手洗', '越南', '實品顏色依單品照為主', 'O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.', 'uploads\\\\woman5.jpg');
INSERT INTO stylish.products (id, category, title, description, price, texture, wash, place, note, story, main_image) VALUES (7, 'women', '質感澎袖綁帶透膚設計兩穿式上衣', '厚薄：薄\\r\\n彈性：無', 600.00, '棉 100%', '手洗', '越南', '實品顏色依單品照為主', 'O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.', 'uploads\\\\woman6.jpg');
INSERT INTO stylish.products (id, category, title, description, price, texture, wash, place, note, story, main_image) VALUES (8, 'women', '簡約圓領造型磨毛感設計五分袖上衣', '厚薄：薄\\r\\n彈性：無', 500.00, '棉 100%', '手洗', '越南', '實品顏色依單品照為主', 'O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.', 'uploads\\\\woman7.jpg');
INSERT INTO stylish.products (id, category, title, description, price, texture, wash, place, note, story, main_image) VALUES (9, 'accessories', '法式小花耳環', '厚薄：薄\\r\\n彈性：無', 240.00, '塑料/銅', '手洗', '韓國', '實品顏色依單品照為主', 'O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.', 'uploads\\\\accessories1.jpg');
